Bump rspec-rails from 3.7.2 to 3.8.2 (#173)
Bumps [rspec-rails](https://github.com/rspec/rspec-rails) from 3.7.2 to 3.8.2.
<details>
<summary>Changelog</summary>

*Sourced from [rspec-rails's changelog](https://github.com/rspec/rspec-rails/blob/master/Changelog.md).*

> ### 3.8.2 / 2019-01-13
> [Full Changelog](http://github.com/rspec/rspec-rails/compare/v3.8.1...v3.8.2)
> 
> Bug Fixes:
> 
> * Fix issue with generator for preview specs where `Mailer` would be duplicated
>   in the name. (Kohei Sugi, [#2037](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2037))
> * Fix the request spec generator to handle namespaced files. (Kohei Sugi, [#2057](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2057))
> * Further truncate system test filenames to handle cases when extra words are
>   prepended. (Takumi Kaji, [#2058](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2058))
> * Backport: Make the `ActiveJob` matchers fail when multiple jobs are queued
>   for negated matches. e.g. `expect { job; job; }.to_not have_enqueued_job
>   (Emric Istanful, [#2069](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2069))
> 
> ### 3.8.1 / 2018-10-23
> [Full Changelog](http://github.com/rspec/rspec-rails/compare/v3.8.0...v3.8.1)
> 
> Bug Fixes:
> 
> * Fix `NoMethodError: undefined method 'strip'` when using a `Pathname` object
>   as the fixture file path. (Aaron Kromer, [#2026](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2026))
> * When generating feature specs, do not duplicate namespace in the path name.
>   (Laura Paakkinen, [#2034](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2034))
> * Prevent `ActiveJob::DeserializationError` from being issued when `ActiveJob`
>   matchers de-serialize arguments. ([**aymeric-ledorze**](https://github.com/aymeric-ledorze), [#2036](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2036))
> 
> ### 3.8.0 / 2018-08-04
> [Full Changelog](http://github.com/rspec/rspec-rails/compare/v3.7.2...v3.8.0)
> 
> Enhancements:
> 
> * Improved message when migrations are pending in the default `rails_helper.rb`
>   (Koichi ITO, [#1924](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/1924))
> * `have_http_status` matcher now supports Rails 5.2 style response symbols
>   (Douglas Lovell, [#1951](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/1951))
> * Change generated Rails helper to match Rails standards for Rails.root
>   (Alessandro Rodi, [#1960](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/1960))
> * At support for asserting enqueued jobs have no wait period attached.
>   (Brad Charna, [#1977](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/1977))
> * Cache instances of `ActionView::Template` used in `stub_template` resulting
>   in increased performance due to less allocations and setup. (Simon Coffey, [#1979](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/1979))
> * Rails scaffold generator now respects longer namespaces (e.g. api/v1/\<thing\>).
>   (Laura Paakkinen, [#1958](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/1958))
> 
> Bug Fixes:
> 
> * Escape quotation characters when producing method names for system spec
>   screenshots. (Shane Cavanaugh, [#1955](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/1955))
> * Use relative path for resolving fixtures when `fixture_path` is not set.
>   (Laurent Cobos, [#1943](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/1943))
></tr></table> ... (truncated)
</details>
<details>
<summary>Commits</summary>

- [`0d0ce9e`](https://github.com/rspec/rspec-rails/commit/0d0ce9e39153f6c952f008c8dc014df3d3f88061) Merge pull request [#2067](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2067) from benoittgt/3-8-maintenance-prep
- [`987bd32`](https://github.com/rspec/rspec-rails/commit/987bd324c1d4a3ce15f1c0313de2cabe9e539614) Update version to 3.8.2
- [`2ae472b`](https://github.com/rspec/rspec-rails/commit/2ae472b775130db0477c09e0afb54d488784ecb8) Backport: Changelog for [#2047](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2047)
- [`9271c22`](https://github.com/rspec/rspec-rails/commit/9271c22a3b92c40ff8e74f22e21cc41f46e0395b) Backport: Change negated active job matcher ([#2069](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2069))
- [`7ca3d04`](https://github.com/rspec/rspec-rails/commit/7ca3d04b2ab2bd38034299b63224e4c2da350840) Downgrade to older bundler on older rails
- [`1c6074f`](https://github.com/rspec/rspec-rails/commit/1c6074f3de917434c6606411cb310e84ccffe7f3) Add dependency for rspec-rails on bundler / rubygems script
- [`081cce5`](https://github.com/rspec/rspec-rails/commit/081cce58bb2d7c536a9c4b17b1aedbc1e9a3d520) Updated travis build scripts (from rspec-dev)
- [`75c02f8`](https://github.com/rspec/rspec-rails/commit/75c02f845ad3470c061c8a7cc509f6b45789aba1) Updated travis build scripts (from rspec-dev) ([#2059](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2059))
- [`79925f9`](https://github.com/rspec/rspec-rails/commit/79925f97242b8969ded2782247d3cfba7cca9e96) Change log for [#2058](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2058)
- [`85b16c4`](https://github.com/rspec/rspec-rails/commit/85b16c4ba73dcb680e2fefaf934d2b9acc5b359d) Truncate method names further in system tests ([#2058](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2058))
- Additional commits viewable in [compare view](https://github.com/rspec/rspec-rails/compare/v3.7.2...v3.8.2)
</details>
<br />

[![Dependabot compatibility score](https://api.dependabot.com/badges/compatibility_score?dependency-name=rspec-rails&package-manager=bundler&previous-version=3.7.2&new-version=3.8.2)](https://dependabot.com/compatibility-score.html?dependency-name=rspec-rails&package-manager=bundler&previous-version=3.7.2&new-version=3.8.2)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot ignore this [patch|minor|major] version` will close this PR and stop Dependabot creating any more for this minor/major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)
- `@dependabot use these labels` will set the current labels as the default for future PRs for this repo and language
- `@dependabot use these reviewers` will set the current reviewers as the default for future PRs for this repo and language
- `@dependabot use these assignees` will set the current assignees as the default for future PRs for this repo and language
- `@dependabot use this milestone` will set the current milestone as the default for future PRs for this repo and language
- `@dependabot badge me` will comment on this PR with code to add a "Dependabot enabled" badge to your readme

Additionally, you can set the following in your Dependabot [dashboard](https://app.dependabot.com):
- Update frequency (including time of day and day of week)
- Automerge options (never/patch/minor, and dev/runtime dependencies)
- Pull request limits (per update run and/or open at any time)
- Out-of-range updates (receive only lockfile updates, if desired)
- Security updates (receive only security updates, if desired)

Finally, you can contact us by mentioning @dependabot.

</details>